@startuml Chat_Entity_Diagram

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam class {
    BackgroundColor #FFFFFF
    BorderColor #000000
    ArrowColor #000000
}

class ChatMessage {
    -Long id
    -ChatRoomType roomType
    -Long roomId
    -String sender
    -String message
    -MessageType type
    -LocalDateTime sentAt
    -Long refId
    -Boolean isSolved
    -Boolean isSelected
    --
    +markAsSolved() : void
    +markAsSelected() : void
}

enum ChatRoomType {
    OPEN
    GROUP
}

enum MessageType {
    ENTER
    TALK
    LEAVE
    IMAGE
    QUESTION
    ANSWER
    SOLVE
}

ChatMessage --> ChatRoomType
ChatMessage --> MessageType

@enduml
