@startuml Chat_Service_Diagram

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam class {
    BackgroundColor #FFFFFF
    BorderColor #000000
    ArrowColor #000000
}

class ChatService {
    -ChatRepository chatRepository
    -MemberRepository memberRepository
    --
    +saveMessage(ChatMessageRequest, String) : ChatMessageResponse
    +solveQuestion(Long, Long, String) : ChatMessage
    +deleteMessage(Long, String) : void
    +getChatHistory(Long, ChatRoomType, int, int) : List<ChatMessage>
}

class ChatRepository {
}

class MemberRepository {
}

ChatService --> ChatRepository
ChatService --> MemberRepository

@enduml
