@startuml Timer_Controller_Diagram

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam class {
    BackgroundColor #FFFFFF
    BorderColor #000000
    ArrowColor #000000
}

class PersonalTimerController {
    -PersonalTimerService personalTimerService
    -PomodoroSettingService pomodoroSettingService
    --
    +startTimer(CustomUser, Long, boolean) : ResponseEntity<TimerStatusResponse>
    +endTimer(CustomUser) : ResponseEntity<Void>
    +toggleTimer(CustomUser) : ResponseEntity<TimerStatusResponse>
    +startPomodoroMode(CustomUser) : ResponseEntity<TimerStatusResponse>
    +stopPomodoroMode(CustomUser) : ResponseEntity<TimerStatusResponse>
    +changePomodoroStatus(CustomUser, TimerStatus) : ResponseEntity<TimerStatusResponse>
    +getTimerStatus(CustomUser) : ResponseEntity<TimerStatusResponse>
    +getStudyTime(CustomUser) : ResponseEntity<StudyTimeResponse>
    +savePomodoroSetting(CustomUser, PomodoroSettingRequest) : ResponseEntity<PomodoroSettingResponse>
    +getPomodoroSetting(CustomUser) : ResponseEntity<PomodoroSettingResponse>
}

class PersonalTimerService {
}

class PomodoroSettingService {
}

PersonalTimerController --> PersonalTimerService
PersonalTimerController --> PomodoroSettingService

@enduml
